import SwiftUI

struct ContentView: View {
    var body: some View {
        
        ZStack{
            Rectangle()
                .fill(Color.green)
                .frame(width:150, height:150)
                .offset(x:250)
            
            Image(systemName: "x.circle.fill")
                .foregroundStyle(.green)
                .font(.largeTitle)
                .bold()
                .offset(x:250)
            
            Rectangle()
                .fill(Color.green)
                .frame(width:150, height:150)
                .offset(x:250,y:250)
            Image(systemName: "x.circle.fill")
                .foregroundStyle(.blue)
                .font(.largeTitle)
                .bold()
                .offset(x:250,y:250)
            
            Rectangle()
                .fill(Color.blue)
                .frame(width:150, height:150)
                .offset()
            Image(systemName: "o.circle.fill")
                .foregroundStyle(.white)
                .font(.largeTitle)
                .bold()
                .offset()
            
            Rectangle()
                .fill(Color.blue)
                .frame(width:150, height:150)
                .offset(y:250)
            Image(systemName: "o.circle.fill")
                .foregroundStyle(.white)
                .font(.largeTitle)
                .bold()
                .offset(y:250)
            
            Rectangle()
                .fill(Color.green)
                .frame(width:150, height:150)
                .offset(x:-250)
            Image(systemName: "x.circle.fill")
                .foregroundStyle(.blue)
                .font(.largeTitle)
                .bold()
                .offset(x:-250)
            
            Rectangle()
                .fill(Color.green)
                .frame(width:150, height:150)
                .offset(x:-250,y:250)
            Image(systemName: "x.circle.fill")
                .foregroundStyle(.blue)
                .font(.largeTitle)
                .bold()
                .offset(x:-250,y:250)
            
            Rectangle()
                .fill(Color.blue)
                .frame(width:150, height:150)
                .offset(y:-250)
            Image(systemName: "o.circle.fill")
                .foregroundStyle(.white)
                .font(.largeTitle)
                .bold()
                .offset(y:-250)
            
            Rectangle()
                .fill(Color.green)
                .frame(width:150, height:150)
                .offset(x:250, y:-250)
            Image(systemName: "x.circle.fill")
                .foregroundStyle(.blue)
                .font(.largeTitle)
                .bold()
                .offset(x:250,y:-250)
            
            Rectangle()
                .fill(Color.green)
                .frame(width:150, height:150)
                .offset(x:-250,y:-250)
            Image(systemName: "x.circle.fill")
                .foregroundStyle(.blue)
                .font(.largeTitle)
                .bold()
                .offset(x:-250,y:-250)
        }
    }
}
